# Default Config File for PureEntitiesX

# set where entities can spawn e.g ["world", "flat"], or leave empty to allow entities to spawn in any level
enabledworlds: []

# set how often the spawn and despawn task will be trigered
spawn-task:
  trigger-ticks: 300
  use-block-light: false
  use-sky-light: false

# after how many ticks an entity gets despawned (if not tamed)
despawn:
  after-ticks: 72000

# configuration of panic mode for some entities
panic:
  enabled: true
  ticks: 100 # how long is an entity in panic mode

# task definitions - to have full functionality, enable all!
tasks:
  spawn: true # set to true to enable spawn/unspawn tasks
  async: true # set to true for mob equipment working and relogging tamed entities working
  looking: true # set to true to enable entity interaction and enderman looking detection e.g.

# when set to true the creeper will explode and also destroy blocks
creeper:
  block-breaking-explosion: false

breeding:
  emit-love-particles-constantly: true

# control logfile logging
# possible: debug, warn, info
# in productional environment info or warn should be set - otherwise it will take a lot of performance!
logfile:
  loglevel: info

# describes the distances that are used for specific actions
distances:
  interact: 3 # defines until which distance an interaction with an entity is possible
  find-partner: 49 # defines whe maximum distance when love mode is active and is searching for another partner
  tamed-teleport: 20 # defines how many blocks the player can move until the tamed entity teleports to it's owner (when not sitting)
  tamed-follow-player: 14 # defines the distance between owner and tamed entity when it stops wandering around and get back to player

ticks:
  block-interest: 100 # defines how many ticks pass by before the block of interest check kicks in

idle:
  chance: 80 # 20 percent of idle after walking around
  min-idle: 100 # minimum idle in ticks
  max-idle: 500 # max idle in ticks
  time-between-idle: 20 # time that has to pass at least between each idling status in seconds

# control max spawning values ...
max-spawn:
  bat: 2
  chicken: 5
  cow: 5
  horse: 10 # also donkeys and so on ...
  ocelot: 2
  parrot: 3
  pig: 5
  rabbit: 5
  sheep: 5

  blaze: 5
  cavespider: 5
  creeper: 5
  enderman: 5
  ghast: 5
  irongolem: 0
  magmacube: 5
  pigzombie: 5
  skeleton: 5
  slime: 5
  spider: 8
  wolf: 5
  zombie: 5


# control spawn probability with each spawn run for each entity
# probability is configured as percent (20 means 20% chance of spawning)
probability:
  bat: 20
  chicken: 20
  cow: 20
  horse: 10
  ocelot: 20
  parrot: 30
  pig: 20
  rabbit: 20
  sheep: 20

  blaze: 10
  cavespider: 20
  creeper: 20
  enderman: 5
  ghast: 10
  irongolem: 1
  magmacube: 10
  pigzombie: 10
  skeleton: 10
  slime: 20
  spider: 20
  wolf: 20
  zombie: 20

# please only tune the following when you know what you're doing ;)
performance:
  check-target-tick-skip: 5 # the lower the value the more performance it takes
  check-interactive-ticks: 10 # how often does the plugin check if an interactive button is displayed - the lesser the value the more performance is needed
  check-interactive-correction: true # setting this to true the interactive button finding is a lot better but more unprecise and consumes more performance
  check-enderman-looking: 10 # how often does the plugin check if a player looks at an enderman
  check-pickup-loot: 10 # how often do entities look after things they can pick up (configure ticks between checks)
  enable-logging: false # enable file logging (set to false for productive environments)
  enable-nbt-storage: true # enable to store to NBT - this has to be set to true to work properly

# mob equipment configuration
mob-equipment:
  # each entity is configured here!
  zombie:
    # chances for pickup loot, wearing armor and weapon in percent for easy|normal|hard
    wear-pickup-chances:
      can-pickup-loot:
        easy: 0
        normal: 55
        hard: 75
      armor:
        easy: 0
        normal: 15
        hard: 20
      weapon:
        easy: 1
        normal: 10
        hard: 20
    # chances of different armor pieces, per difficulty (easy|normal|hard)
    wear-chances:
      helmet:
        easy: 100
        normal: 100
        hard: 100
      helmet-chestplate:
        easy: 75
        normal: 75
        hard: 90
      helmet-chestplate-leggings:
        easy: 56
        normal: 56
        hard: 81
      full:
        easy: 42
        normal: 42
        hard: 73
    # chances of different armor pieces, per difficulty
    armor-types:
      leather: 37
      gold: 48
      chain: 13 # not used yet
      iron: 2
      diamond: 1

  zombiepigman:
      # chances for pickup loot, wearing armor and weapon in percent for easy|normal|hard
      wear-pickup-chances:
        can-pickup-loot:
          easy: 0
          normal: 55
          hard: 75
        armor:
          easy: 0
          normal: 15
          hard: 20
        weapon:
          easy: 1
          normal: 10
          hard: 20
      # chances of different armor pieces, per difficulty (easy|normal|hard)
      wear-chances:
        helmet:
          easy: 100
          normal: 100
          hard: 100
        helmet-chestplate:
          easy: 75
          normal: 75
          hard: 90
        helmet-chestplate-leggings:
          easy: 56
          normal: 56
          hard: 81
        full:
          easy: 42
          normal: 42
          hard: 73
      # chances of different armor pieces, per difficulty
      armor-types:
        leather: 37
        gold: 48
        chain: 13 # not used yet
        iron: 2
        diamond: 1